<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Catalog\Block\Product\View\Attributes;
use Magento\Catalog\Helper\Output as CatalogOutputHelper;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var CatalogOutputHelper $output */
/** @var Attributes $block */
/** @var ViewModelRegistry $viewModels */

$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var CatalogOutputHelper $catalogOutputHelper */
$catalogOutputHelper = $this->helper(CatalogOutputHelper::class);

/** @var Product $product */
$product = $block->getProduct();
?>


<?php if ($attributes = $block->getAdditionalData()): ?>
    <div
        class="animate-on-transition mx-4 mb-8 flex flex-col overflow-hidden rounded-md border-1 border-bg-sunken bg-surface px-4 md:mx-0 md:px-5"
        x-data="Accordion(false, 300)"
    >
        <button
            class="group flex w-full items-center justify-between gap-3 py-4 text-start"
            x-ref="AccordionButton"
            type="button"
            :aria-expanded="isExpanded"
            aria-controls="attributes_panel"
            aria-labelledby="attributes_label"
        >
            <div id="attributes_label" class="text-base font-semibold leading-tight text-fg">
                <?= $block->getTitle() ? $escaper->escapeHtml($block->getTitle()) : '&nbsp;' ?>
            </div>
            <span x-ref="AccordionIcon"
                  class="button button--outline-secondary icon-button icon-button--size-xs group-hoverable">
                <?= $hyvaicons->renderHtml('chevron', 'rotate-90', attributes: ['title' => '']); ?>
            </span>
        </button>
        <div
            x-ref="AccordionPanel"
            :inert="!isExpanded"
            role="region"
            class="overflow-hidden"
            id="attributes_panel"
            aria-labelledby="attributes_label"
            style="max-height: 0;"
        >
            <div class="border-t border-bg-sunken py-2">
                <div class="table-wrapper overflow-x-auto" id="product-attributes">
                    <table class="additional-attributes w-full">
                        <?php foreach ($attributes as $attribute): ?>
                            <tr class="border-b border-bg-sunken last:border-b-0">
                                <th
                                    class="col label w-1/2 py-3 text-left font-normal text-fg-secondary product-attribute-label"
                                    scope="row"
                                >
                                    <?= $escaper->escapeHtml($attribute['label']) ?>
                                </th>
                                <td
                                    class="col data w-1/2 py-3 pl-3 text-left font-medium text-fg product-attribute-value"
                                    data-th="<?= $escaper->escapeHtmlAttr($attribute['label']) ?>"
                                >
                                    <?= /* @noEscape */ $catalogOutputHelper->productAttribute($product, $attribute['value'], $attribute['code']) ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
