<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template as Block;
use Satoshi\Theme\Block\Template;

/** @var Block $block */
/** @var Template $template */
/** @var Escaper $escaper */

$minPriceRange = (int)$block->getData('min_price_range') ?? 0;
$maxPriceRange = (int)$block->getData('max_price_range') ?? '';
?>
<div x-data="RangeSlider(<?= $minPriceRange ?>, <?= $maxPriceRange ?>)">
    <div class="grid grid-cols-2 gap-3 mb-5">
        <label for="filter-current-min-price" class="range-slider-input">
            <div class="range-slider-input-label">
                <p><?= __('Min') ?></p>
            </div>
            <input
                name="min-price"
                id="filter-current-min-price"
                class="input__field range-slider-input-field"
                type="number"
                :min="minRange"
                :max="currentMaxValue"
                :value="currentMinValue"
                x-model="currentMinValue"
                @input.blur="updateThumbPositions"
                aria-label="<?= __('Min') ?>"
            />
        </label>

        <label for="filter-current-max-price" class="range-slider-input">
            <div class="range-slider-input-label">
                <p><?= __('Max') ?></p>
            </div>
            <input
                name="max-price"
                id="filter-current-max-price"
                class="input__field range-slider-input-field"
                type="number"
                :min="currentMinValue"
                :max="maxRange"
                :value="currentMaxValue"
                x-model="currentMaxValue"
                @input.blur="updateThumbPositions"
                aria-label="<?= __('Max') ?>"
            />
        </label>
    </div>

</div>
